import 'package:flutter/material.dart';
import 'dart:math';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:trade_quest/l10n/generated/app_localizations.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/services/gemini_service.dart';
import '../../../../core/services/supabase_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late Future<List<Map<String, dynamic>>> _questsFuture;
  String _selectedCategory = 'All Quests';
  Map<String, dynamic>? _profile;
  Set<String> _completedQuestIds = {};
  final TextEditingController _searchController = TextEditingController();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _checkAndRefreshQuests();
      _loadProfile();
      _checkOpenMicStatus();
    });
  }

  Future<void> _loadProfile() async {
    final user = SupabaseService().currentUser;
    if (user != null) {
      final profile = await SupabaseService().getProfile(user.id);
      final completedIds = await SupabaseService().getCompletedQuestIds(user.id);
      
      if (mounted) {
        setState(() {
          _profile = profile;
          _completedQuestIds = completedIds;
        });

        // Progressive Profiling: Check if Onboarding (Knowledge Level) is missing
        if (profile != null && profile['knowledge_level'] == null) {
          context.go('/onboarding');
        }
      }
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _fetchQuests();
  }

  Future<void> _checkAndRefreshQuests() async {
    final language = Localizations.localeOf(context).languageCode;
    
    // Use SharedPreferences to track the last actual generation time
    final prefs = await SharedPreferences.getInstance();
    final lastRefreshMillis = prefs.getInt('last_quest_refresh_${language}') ?? 0;
    final lastRefresh = DateTime.fromMillisecondsSinceEpoch(lastRefreshMillis);
    
    final now = DateTime.now();
    final difference = now.difference(lastRefresh);
    
    // DEBUG: 24h cooldown
    if (difference.inHours >= 24) {
      print('Quests are stale (Last refresh: $lastRefresh). Generating fresh content...');
      
      // Fetch existing titles to exclude them
      final allQuests = await SupabaseService().getQuests(language: language);
      final existingTitles = allQuests.map((q) => q['title'] as String).toList();
      
      try {
        final newQuests = await GeminiService().getAvailableQuests(
            excludedTitles: existingTitles,
            language: language,
        );
        
        if (newQuests.isNotEmpty) {
           final questsToSave = newQuests.map((q) => {...q, 'language': language}).toList();
           await SupabaseService().saveQuests(questsToSave);
           
           // Update timestamp ONLY on success
           await prefs.setInt('last_quest_refresh_${language}', now.millisecondsSinceEpoch);
           print('Fresh quests saved to DB. Timestamp updated.');
        } else {
           print('No new quests generated by AI.');
        }
      } catch (e) {
        print('Smart Refresh failed: $e');
      }
    } else {
      print('Quests are fresh. Next refresh in ${24 - difference.inHours} hours.');
    }

    _fetchQuests();
  }

  void _fetchQuests() {
    final language = Localizations.localeOf(context).languageCode;
    _questsFuture = SupabaseService().getQuests(category: _selectedCategory, language: language);
  }

  int _openMicAttempts = 2;
  DateTime? _openMicUnlockDate;

  Future<void> _checkOpenMicStatus() async {
    final prefs = await SharedPreferences.getInstance();
    final unlockStr = prefs.getString('open_mic_unlock_date');
    final attempts = prefs.getInt('open_mic_attempts') ?? 2;

    DateTime? unlockDate;
    if (unlockStr != null) {
      unlockDate = DateTime.parse(unlockStr);
    }
    
    // Logic: If locked and date passed -> Reset
    if (unlockDate != null && DateTime.now().isAfter(unlockDate)) {
       await prefs.setInt('open_mic_attempts', 2);
       await prefs.remove('open_mic_unlock_date');
       
       if (mounted) {
         setState(() {
           _openMicAttempts = 2;
           _openMicUnlockDate = null;
         });
       }
    } else {
      if (mounted) {
        setState(() {
          _openMicAttempts = attempts;
          _openMicUnlockDate = unlockDate;
        });
      }
    }
  }

  Future<void> _consumeOpenMicAttempt() async {
    final prefs = await SharedPreferences.getInstance();
    int newAttempts = _openMicAttempts - 1;
    
    if (newAttempts <= 0) {
      final unlockDate = DateTime.now().add(const Duration(days: 3));
      await prefs.setString('open_mic_unlock_date', unlockDate.toIso8601String());
      await prefs.setInt('open_mic_attempts', 0);
      setState(() {
        _openMicAttempts = 0;
        _openMicUnlockDate = unlockDate;
      });
    } else {
      await prefs.setInt('open_mic_attempts', newAttempts);
      setState(() {
        _openMicAttempts = newAttempts;
      });
    }
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  void _onCategorySelected(String category) {
    setState(() {
      _selectedCategory = category;
      _fetchQuests();
    });
  }

  void _showOpenMicDialog() {
    if (_openMicAttempts <= 0 && _openMicUnlockDate != null) {
      return; // Should be hidden, but extra safety
    }

    final TextEditingController controller = TextEditingController();
    
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        backgroundColor: const Color(0xFF1E293B),
        title: Row(
          children: [
            const Text('Open Mic 🎤', style: TextStyle(color: Colors.white)),
            const Spacer(),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(
                color: AppColors.primary.withOpacity(0.2),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Text(
                '$_openMicAttempts left', 
                style: const TextStyle(color: AppColors.primary, fontSize: 10, fontWeight: FontWeight.bold)
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Ask the AI to teach you a specific financial concept.',
              style: TextStyle(color: Colors.white70, fontSize: 13),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: controller,
              style: const TextStyle(color: Colors.white),
              decoration: InputDecoration(
                hintText: 'e.g. Short Selling, ETF, Greeks...',
                hintStyle: TextStyle(color: Colors.white.withOpacity(0.3)),
                filled: true,
                fillColor: Colors.black26,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext),
            child: const Text('Cancel', style: TextStyle(color: Colors.white54)),
          ),
          ElevatedButton(
            onPressed: () async {
              final topic = controller.text.trim();
              if (topic.isEmpty) return;
              
              Navigator.pop(dialogContext); // Close dialog
              
              // Consume Attempt
              await _consumeOpenMicAttempt();

              // 1. Show loading snippet (optional)
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Analyzing Request...')),
              );

              // 2. Create Placeholder Quest in DB
              final questId = await SupabaseService().createCustomQuest(topic);
              
              if (questId != null && mounted) {
                 // 3. Start Lesson
                 await context.push('/lesson?topic=${Uri.encodeComponent(topic)}&level=Custom&questId=$questId');
                 // Refresh when back
                 _loadProfile();
                 _fetchQuests();
              } else {
                 if (mounted) {
                   ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Failed to initialize quest. Try again.')),
                   );
                 }
              }
            },
            style: ElevatedButton.styleFrom(backgroundColor: AppColors.neonPurple),
            child: const Text('Start Lesson', style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      floatingActionButton: (_openMicAttempts > 0) ? FloatingActionButton.extended(
        onPressed: _showOpenMicDialog,
        backgroundColor: AppColors.neonPurple,
        icon: const Icon(Icons.mic, color: Colors.white),
        label: const Text('Open Mic', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
      ) : null,
      body: Stack(
        children: [
          // Background Grid Effect
          Positioned.fill(
            child: Opacity(
              opacity: 0.4,
              child: SvgPicture.network(
                'https://grainy-gradients.vercel.app/noise.svg', 
                fit: BoxFit.cover,
                placeholderBuilder: (_) => const SizedBox(), 
              ),
            ),
          ),

          SafeArea(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // 1. Header
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 12.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                          Text(
                            l10n.selectMission,
                            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                              shadows: [
                                Shadow(
                                  color: Colors.white.withOpacity(0.3),
                                  blurRadius: 8,
                                )
                              ],
                            ),
                          ),
                          const SizedBox(height: 4),
                        ],
                      ),
                    ),
                    
                    GestureDetector(
                      onTap: () => context.push('/solver'),
                      child: Container(
                        margin: const EdgeInsets.only(right: 12),
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: AppColors.neonBlue.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: AppColors.neonBlue.withOpacity(0.3)),
                        ),
                        child: const Icon(Icons.calculate, color: AppColors.neonBlue, size: 24),
                      ),
                    ),

                      GestureDetector(
                        onTap: () => context.go('/profile'),
                        child: Container(
                          padding: const EdgeInsets.only(left: 12, right: 4, top: 4, bottom: 4),
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.05),
                            borderRadius: BorderRadius.circular(30),
                            border: Border.all(color: Colors.white.withOpacity(0.1)),
                          ),
                          child: Row(
                            children: [
                              Text(
                                '${l10n.level} ${_calculateLevel(_profile?['xp'] ?? 0)}'),
                              const SizedBox(width: 8),
                              Container(
                                width: 32,
                                height: 32,
                                decoration: BoxDecoration(
                                  shape: BoxShape.circle,
                                  gradient: const LinearGradient(
                                    colors: [AppColors.primary, AppColors.neonPurple],
                                    begin: Alignment.bottomLeft,
                                    end: Alignment.topRight,
                                  ),
                                ),
                                child: Padding(
                                  padding: const EdgeInsets.all(2.0),
                                  child: Container(
                                    decoration: const BoxDecoration(
                                      color: AppColors.backgroundDark,
                                      shape: BoxShape.circle,
                                    ),
                                    child: const Icon(Icons.person, size: 18, color: Colors.white),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                
                SizedBox(
                  height: 60,
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                    children: [
                      _buildChip('All Quests', isActive: _selectedCategory == 'All Quests', onTap: () => _onCategorySelected('All Quests')),
                      _buildChip('Crypto', isActive: _selectedCategory == 'Crypto', onTap: () => _onCategorySelected('Crypto')),
                      _buildChip('Stocks', isActive: _selectedCategory == 'Stocks', onTap: () => _onCategorySelected('Stocks')),
                      _buildChip('RealEstate', isActive: _selectedCategory == 'RealEstate', onTap: () => _onCategorySelected('RealEstate')),
                      _buildChip('Business', isActive: _selectedCategory == 'Business', onTap: () => _onCategorySelected('Business')),
                      _buildChip('Psychology', isActive: _selectedCategory == 'Psychology', onTap: () => _onCategorySelected('Psychology')),
                      _buildChip('Law', isActive: _selectedCategory == 'Law', onTap: () => _onCategorySelected('Law')),
                    ],
                  ),
                ),

                Expanded(
                  child: FutureBuilder<List<Map<String, dynamic>>>(
                    future: _questsFuture,
                    builder: (context, snapshot) {
                      if (snapshot.connectionState == ConnectionState.waiting) {
                         return const Center(child: CircularProgressIndicator(color: AppColors.primary));
                      }
                      
                      final quests = snapshot.data ?? [];
                      final featuredQuest = quests.firstWhere(
                        (q) => q['title'] == 'Bitcoin Basics', 
                        orElse: () => quests.isNotEmpty ? quests.first : <String, dynamic>{},
                      );
                      
                      return ListView(
                        padding: const EdgeInsets.only(left: 24, right: 24, bottom: 100),
                        children: [
                          // Featured Card
                          _buildFeaturedCard(context, l10n, featuredQuest),
                          
                          const SizedBox(height: 24),
                          
                          // "Available Quests" Header
                          Row(
                            children: [
                               Icon(Icons.grid_view, color: AppColors.neonPurple, size: 20),
                               const SizedBox(width: 8),
                               Text(
                                 'Available Quests',
                                 style: Theme.of(context).textTheme.titleLarge?.copyWith(
                                   fontWeight: FontWeight.bold,
                                   color: Colors.white,
                                 ),
                               ),
                            ],
                          ),
                          
                          const SizedBox(height: 16),
                          
                          if (snapshot.hasError)
                            const Padding(
                              padding: EdgeInsets.all(16.0),
                              child: Center(child: Text("System Offline. Check Connection.", style: TextStyle(color: Colors.red))),
                            )
                          else
                            Column(
                              children: quests.map((q) {
                                 // Don't show featured quest in the list
                                 if (q['title'] == featuredQuest['title']) return const SizedBox.shrink();
                                 
                                 return _buildQuestTile(
                                   context,
                                   title: q['title'] ?? 'Unknown',
                                   subtitle: q['subtitle'] ?? 'General',
                                   tag: q['tag'] ?? 'Task',
                                   tagColor: _getColorForTag(q['tag']),
                                   xp: q['xp'] ?? 100,
                                   icon: _getIconForName(q['icon']),
                                   description: q['description'] ?? 'No intel available.',
                                   questId: q['id'] ?? 'unknown',
                                   isCompleted: _completedQuestIds.contains(q['id'] ?? ''),
                                   isLocked: _isQuestLocked(q),
                                 ).animate().fadeIn().slideX();
                              }).toList(),
                            ),
                        ],
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
          
          // Bottom Blur Fade
          Positioned(
            bottom: 0,
            left: 0,
            right: 0,
            height: 80,
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    AppColors.backgroundDark.withOpacity(0),
                    AppColors.backgroundDark,
                  ],
                ),
              ),
            ),
          )
        ],
      ),
    );
  }

  Color _getColorForTag(String? tag) {
     if (tag == 'Beginner') return AppColors.neonGreen;
     if (tag == 'Expert') return AppColors.neonRed;
     if (tag == 'Intermediate') return Colors.amber;
     if (tag == 'Legendary') return const Color(0xFFFFD700); // Gold
     if (tag == 'Entrepreneur') return const Color(0xFF4169E1); // Royal Blue
     return AppColors.neonBlue;
  }
  
  IconData _getIconForName(String? name) {
    if (name == 'wallet') return Icons.account_balance_wallet;
    if (name == 'chart') return Icons.candlestick_chart;
    if (name == 'warning') return Icons.warning_amber;
    if (name == 'currency') return Icons.currency_bitcoin;
    if (name == 'brain') return Icons.psychology;
    if (name == 'house') return Icons.house;
    if (name == 'globe') return Icons.public;
    if (name == 'robot') return Icons.smart_toy;
    if (name == 'shield') return Icons.security;
    if (name == 'rocket') return Icons.rocket_launch;
    if (name == 'building') return Icons.apartment;
    if (name == 'briefcase') return Icons.work;
    return Icons.token;
  }

  bool _isQuestLocked(Map<String, dynamic> quest) {
    if (_profile == null) return true; // Lock if profile not loaded
    
    final int userXp = _profile!['xp'] as int? ?? 0;
    final String tag = quest['tag'] ?? 'Beginner';
    
    // Quadratic thresholds: XP = 2500 * (Level-1)^2
    // Level 2 (Intermediate) = 2500 XP
    // Level 3 (Expert) = 10000 XP
    // Level 4 (Entrepreneur) = 22500 XP
    // Level 5 (Legendary) = 40000 XP
    
    if (tag == 'Beginner') return false;
    if (tag == 'Intermediate') return userXp < 2500;
    if (tag == 'Expert') return userXp < 10000;
    if (tag == 'Entrepreneur') return userXp < 22500;
    if (tag == 'Legendary') return userXp < 40000;
    
    return false;
  }

  int _calculateLevel(int xp) {
    if (xp <= 0) return 1;
    // Formula: Level = floor(sqrt(XP / 2500)) + 1
    // L1 = 0-2499, L2 = 2500-9999, etc.
    return (sqrt(xp / 2500).floor()) + 1;
  }

  Widget _buildChip(String label, {bool isActive = false, VoidCallback? onTap}) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        margin: const EdgeInsets.only(right: 8),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
        decoration: BoxDecoration(
          color: isActive ? AppColors.primary.withOpacity(0.2) : Colors.white.withOpacity(0.05),
          borderRadius: BorderRadius.circular(30),
          border: Border.all(
            color: isActive ? AppColors.primary.withOpacity(0.5) : Colors.white.withOpacity(0.1),
          ),
          boxShadow: isActive ? [
            BoxShadow(
              color: AppColors.primary.withOpacity(0.2),
              blurRadius: 10,
            )
          ] : [],
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              color: isActive ? AppColors.primary : AppColors.textSecondary,
              fontSize: 12,
              fontWeight: isActive ? FontWeight.bold : FontWeight.w500,
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildFeaturedCard(BuildContext context, AppLocalizations l10n, Map<String, dynamic> quest) {
    if (quest.isEmpty) return const SizedBox.shrink();

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(24),
        gradient: const LinearGradient(
          colors: [Color(0xFF1E293B), Color(0xFF0F172A)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        border: Border.all(
          color: AppColors.primary.withOpacity(0.3),
          width: 1,
        ),
        image: const DecorationImage(
          image: NetworkImage("https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=2938&auto=format&fit=crop"), // Abstract Tech
          fit: BoxFit.cover,
          opacity: 0.2,
        ),
        boxShadow: [
          BoxShadow(
            color: AppColors.primary.withOpacity(0.1),
            blurRadius: 30,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: AppColors.primary.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: AppColors.primary.withOpacity(0.2)),
                ),
                child: const Text(
                  'FEATURED',
                  style: TextStyle(
                    color: AppColors.primary,
                    fontWeight: FontWeight.bold,
                    fontSize: 10,
                    letterSpacing: 1.0,
                  ),
                ),
              ),
              Container(
                width: 32,
                height: 32,
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.05),
                  shape: BoxShape.circle,
                  border: Border.all(color: Colors.white.withOpacity(0.1)),
                ),
                child: const Icon(Icons.bookmark_border, size: 18, color: Colors.white),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                     Text(
                      quest['title'] ?? 'Bitcoin: The Beginning',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        height: 1.2,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      quest['description'] ?? 'Travel back to 2009. Mine the first block and learn the core of blockchain technology.',
                      style: TextStyle(
                        color: AppColors.textSecondary,
                        fontSize: 12,
                        height: 1.5,
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 20),
                    Wrap(
                      crossAxisAlignment: WrapCrossAlignment.center,
                      spacing: 12,
                      runSpacing: 8,
                      children: [
                        GestureDetector(
                          onTap: () async {
                            await context.push('/lesson?topic=${quest['title']}&level=${quest['tag']}&questId=${quest['id']}&xpReward=${quest['xp'] ?? 100}');
                             // Refresh data when finding back
                            _loadProfile();
                            _fetchQuests();
                          },
                          child: Container(
                            padding: const EdgeInsets.only(left: 16, right: 12, top: 10, bottom: 10),
                            decoration: BoxDecoration(
                              color: AppColors.primary,
                              borderRadius: BorderRadius.circular(30),
                              boxShadow: [
                                BoxShadow(
                                  color: AppColors.primary.withOpacity(0.4),
                                  blurRadius: 10,
                                  offset: const Offset(0, 4),
                                ),
                              ],
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                const Text(
                                  'Start Mission',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 12,
                                  ),
                                ),
                                const SizedBox(width: 8),
                                const Icon(Icons.arrow_forward, size: 14, color: Colors.white),
                              ],
                            ),
                          ),
                        ),
                      ],

                    ),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              // Image Placeholder
              Container(
                width: 100,
                height: 100,
                 decoration: BoxDecoration(
                  color: AppColors.primary.withOpacity(0.1),
                  shape: BoxShape.circle,
                ),
                child: Center(
                  child: Icon(Icons.currency_bitcoin, size: 50, color: AppColors.primary),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildQuestTile(
    BuildContext context, {
    required String title,
    required String subtitle,
    required String tag,
    required Color tagColor,
    required int xp,
    required IconData icon,
    required String description,
    required String questId,
    bool isLocked = false,
    bool isCompleted = false,
  }) {
    return GestureDetector(
      onTap: (isLocked || isCompleted) ? null : () async {
        if (isLocked) return; // double check
        await context.push('/lesson?topic=${Uri.encodeComponent(title)}&level=${Uri.encodeComponent(tag)}&questId=$questId&xpReward=$xp');
        // Refresh data when returning
        _loadProfile();
        _fetchQuests();
      },
      child: Container(
        margin: const EdgeInsets.only(bottom: 16),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: const Color(0xFF162229).withOpacity(isLocked ? 0.5 : 1.0),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
             color: isCompleted ? AppColors.neonGreen.withOpacity(0.5) : Colors.white.withOpacity(0.05)
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.1),
              blurRadius: 10,
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              children: [
                // Icon Box
                Container(
                  width: 44,
                  height: 44,
                  decoration: BoxDecoration(
                    color: isCompleted ? AppColors.neonGreen.withOpacity(0.1) : tagColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                       color: isCompleted ? AppColors.neonGreen.withOpacity(0.2) : tagColor.withOpacity(0.2)
                    ),
                  ),
                  child: Icon(
                    isLocked ? Icons.lock : (isCompleted ? Icons.check : icon), 
                    color: isLocked ? Colors.grey : (isCompleted ? AppColors.neonGreen : tagColor), 
                    size: 24
                  ),
                ),
                const SizedBox(width: 12),
                
                // Titles
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        title,
                        style: TextStyle(
                          color: isCompleted ? Colors.white.withOpacity(0.5) : Colors.white,
                          decoration: isCompleted ? TextDecoration.lineThrough : null,
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      Text(
                        isCompleted ? 'Mission Accomplished' : subtitle,
                        style: TextStyle(
                          color: isCompleted ? AppColors.neonGreen : AppColors.textSecondary,
                          fontSize: 12,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                ),
                
                const SizedBox(width: 8),

                // Tag Badge
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: tagColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(6),
                    border: Border.all(color: tagColor.withOpacity(0.2)),
                  ),
                  child: Text(
                    tag.toUpperCase(),
                    style: TextStyle(
                      color: tagColor,
                      fontWeight: FontWeight.bold,
                      fontSize: 10,
                      letterSpacing: 0.5,
                    ),
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 12),
            
            Text(
              description,
              style: TextStyle(
                color: AppColors.textSecondary,
                fontSize: 14,
                height: 1.5,
              ),
            ),
            
            const SizedBox(height: 16),
            
            // Footer
            Container(
              padding: const EdgeInsets.only(top: 12),
              decoration: BoxDecoration(
                border: Border(top: BorderSide(color: Colors.white.withOpacity(0.05))),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: [
                      Icon(Icons.bolt, color: isCompleted ? AppColors.textSecondary : AppColors.neonPurple, size: 16),
                      const SizedBox(width: 4),
                      Text(
                        isLocked ? '??? XP' : (isCompleted ? 'Claimed' : '+$xp XP'),
                        style: TextStyle(
                          color: isLocked || isCompleted ? AppColors.textSecondary : Colors.white,
                          fontWeight: FontWeight.bold,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                  Icon(
                    isLocked ? Icons.lock : (isCompleted ? Icons.check_circle : Icons.arrow_forward),
                    color: isCompleted ? AppColors.neonGreen : AppColors.textSecondary,
                    size: 20,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
}
}
